# Site settings
author: James Pier
title: jimDev
header-img: img/home-bg.png
email: jpier2012@gmail.com
copyright_name: James Pier
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jpier2012

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
